export const LangFieldSchema = {
    en_US: String,
    ar_AE: String,
    zh_CN: String,
    zh_TW: String,
    cs_CZ: String,
    da_DK: String,
    nl_NL: String,
    fr_FR: String,
    de_DE: String,
    in_ID: String,
    it_IT: String,
    ja_JP: String,
    ko_KR: String,
    ms_MY: String,
    no_NO: String,
    pl_PL: String,
    pt_BR: String,
    ro_RO: String,
    ru_RU: String,
    es_ES: String,
    sv_SE: String,
    tl_PH: String,
    th_TH: String,
    tr_TR: String
}

export interface LangField  {
    en_US: string,
    ar_AE: string,
    zh_CN: string,
    zh_TW: string,
    cs_CZ: string,
    da_DK: string,
    nl_NL: string,
    fr_FR: string,
    de_DE: string,
    in_ID: string,
    it_IT: string,
    ja_JP: string,
    ko_KR: string,
    ms_MY: string,
    no_NO: string,
    pl_PL: string,
    pt_BR: string,
    ro_RO: string,
    ru_RU: string,
    es_ES: string,
    sv_SE: string,
    tl_PH: string,
    th_TH: string,
    tr_TR: string
}